package com.luanmuc.openwrtmanager.ui.theme

import androidx.compose.ui.graphics.Color

// 蓝色系主题色 - 小米/华为风格
val BluePrimary = Color(0xFF1677FF)
val BluePrimaryDark = Color(0xFF0958D9)
val BlueLight = Color(0xFF4096FF)
val BlueGradientStart = Color(0xFF1677FF)
val BlueGradientEnd = Color(0xFF4096FF)

// 浅色主题色
val md_theme_light_primary = Color(0xFF1677FF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD6E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
val md_theme_light_secondary = Color(0xFF545F70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD8E3F7)
val md_theme_light_onSecondaryContainer = Color(0xFF111C2B)
val md_theme_light_tertiary = Color(0xFF6B5778)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF3DAFF)
val md_theme_light_onTertiaryContainer = Color(0xFF251431)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8F9FA)
val md_theme_light_onBackground = Color(0xFF191C20)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF191C20)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
val md_theme_light_inverseSurface = Color(0xFF2E3135)
val md_theme_light_inversePrimary = Color(0xFFAAC7FF)
val md_theme_light_surfaceTint = Color(0xFF1677FF)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)

// 深色主题色
val md_theme_dark_primary = Color(0xFFAAC7FF)
val md_theme_dark_onPrimary = Color(0xFF00325B)
val md_theme_dark_primaryContainer = Color(0xFF004980)
val md_theme_dark_onPrimaryContainer = Color(0xFFD6E4FF)
val md_theme_dark_secondary = Color(0xFFBCC7DB)
val md_theme_dark_onSecondary = Color(0xFF263141)
val md_theme_dark_secondaryContainer = Color(0xFF3C4858)
val md_theme_dark_onSecondaryContainer = Color(0xFFD8E3F7)
val md_theme_dark_tertiary = Color(0xFFD7BDE4)
val md_theme_dark_onTertiary = Color(0xFF3B2948)
val md_theme_dark_tertiaryContainer = Color(0xFF523F5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFF3DAFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C20)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF191C20)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9199)
val md_theme_dark_inverseOnSurface = Color(0xFF191C20)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inversePrimary = Color(0xFF1677FF)
val md_theme_dark_surfaceTint = Color(0xFFAAC7FF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF1677FF)

// 功能图标渐变色
val GradientBlue = listOf(Color(0xFF1677FF), Color(0xFF4096FF))
val GradientGreen = listOf(Color(0xFF00B578), Color(0xFF36CFC9))
val GradientOrange = listOf(Color(0xFFFF7D00), Color(0xFFFFA940))
val GradientPurple = listOf(Color(0xFF722ED1), Color(0xFF9254DE))
val GradientRed = listOf(Color(0xFFF53F3F), Color(0xFFFF7875))
val GradientCyan = listOf(Color(0xFF13C2C2), Color(0xFF36CFC9))
